---
# tasks file for docker
- name: Install yum utils
  yum:
    name: yum-utils
    state: latest
    
- name: Install docker
  yum : 
    name: docker
    state: present 

- name: enable and start docker
  service:
    name: docker
    state: started
    enabled: yes

